dataPath1: C:/Users/Jeming/Desktop/ra/data/NonsurgicalMR
dataPath2: C:/Users/Jeming/Desktop/ra/data/SurgicalMR
# checkModels: ['A', 'ADC', 'T2_FS', 'V', 'DWI', 'P']
checkModels: ['ADC', 'T2_FS']
lowestResolution: [200, 200]
lowestSize: 500
writePath: data